name: Update, Refilter, and Merge Switchy Omega Lists

on:
  schedule:
    - cron: "0 1 * * *"  # Запуск каждый день в 01:00 UTC
  workflow_dispatch:      # Возможность ручного запуска

jobs:
  update-refilter:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout repository
        uses: actions/checkout@v4

      # Шаг 2: Установка Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # Шаг 3: Установка зависимостей
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # Шаг 4: Запуск скрипта для скачивания, обработки и объединения списков
      - name: Run Switchy Omega Script
        run: python switchy_list_refilter.py

      # Шаг 5: Коммит и пуш изменений
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"
          git add "Refilter+antifilter community.txt"
          git commit -m "Automated refilter and merge: Switchy Omega lists"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
